version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore HybridScaffolding/HybridScaffolding.sln
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: gnO635t5s7bieXHc1NPnfmKcgoJZYfu9Zpr0oE5v1Bm98+TPZX/ckGaA8HZ6Z/sb
  skip_symbols: true